/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CarRentalUI;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivanirahatwad
 */
public class RentCar extends javax.swing.JFrame {

    /**
     * Creates new form RentCar
     */
    public RentCar() {
        initComponents();
          LoadCar_iD();
//        jDateChooser_Rent.setDateFormatString("yyyy-MM-dd");
//        jDateChooser_Return.setDateFormatString("yyyy-MM-dd");

        Update_Table();
        autoID();
    }
    public void LoadCar_iD() {
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            PreparedStatement pstmt = c.prepareStatement("SELECT * FROM CARS ");
            ResultSet rs = pstmt.executeQuery();
            jComboBox_Rent.removeAllItems();

            while (rs.next()) 
            {
                jComboBox_Rent.addItem(rs.getString(1));

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public void autoID() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            Statement s = c.createStatement();

            ResultSet rs = s.executeQuery("SELECT MAX(RENT_ID) FROM RENT");
            rs.next();
            rs.getString("MAX(RENT_ID)");

            if (rs.getString("MAX(RENT_ID)") == null) {
                txtRentId.setText("R0001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(RENT_ID)").substring(2, rs.getString("MAX(RENT_ID)").length()));
                id++;

                txtRentId.setText("R0" + String.format("%03d", id));

            }

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtCustomer_Id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRent = new javax.swing.JTable();
        txtFirst_Name = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLast_Name = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        jComboBox_PickUp = new javax.swing.JComboBox<>();
        lblLastName = new javax.swing.JLabel();
        jComboBox_Drop = new javax.swing.JComboBox<>();
        txtRentDate = new javax.swing.JLabel();
        txtReturnDate = new javax.swing.JLabel();
        lblPickUp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblCarId = new javax.swing.JLabel();
        jComboBox_Rent = new javax.swing.JComboBox<>();
        lblRentId = new javax.swing.JLabel();
        txtRentId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Price:");

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCustomer_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_IdActionPerformed(evt);
            }
        });
        txtCustomer_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomer_IdKeyPressed(evt);
            }
        });

        jTableRent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Car Id", "Model", "Make", "Status", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRent);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Customer Id:");

        txtLast_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLast_NameKeyReleased(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFirstName.setText("First Name:");

        jComboBox_PickUp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roxbury", "Jamaica Plain", "Mission Park", "Back Bay" }));
        jComboBox_PickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PickUpActionPerformed(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblLastName.setText("Last Name:");

        jComboBox_Drop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roxbury", "Jamaica Plain", "Mission Park", "Back Bay" }));

        txtRentDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtRentDate.setText("Rent Date:");

        txtReturnDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtReturnDate.setText("Return Date:");

        lblPickUp.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblPickUp.setText("Pick Up:");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Rent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Drop:");

        lblCarId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCarId.setText("Car Id:");

        jComboBox_Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RentActionPerformed(evt);
            }
        });

        lblRentId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRentId.setText("Rent_Id:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel2.setText("Rent A Car");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblFirstName)
                        .addGap(38, 38, 38)
                        .addComponent(txtFirst_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(lblLastName)
                        .addGap(19, 19, 19)
                        .addComponent(txtLast_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel8)
                        .addGap(45, 45, 45)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jButton1)
                        .addGap(48, 48, 48)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(lblPickUp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(txtRentDate)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jComboBox_PickUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jComboBox_Drop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(txtReturnDate)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarId)
                                .addGap(58, 58, 58)
                                .addComponent(jComboBox_Rent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblRentId)))
                        .addGap(8, 8, 8)
                        .addComponent(txtRentId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(txtCustomer_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRentId)
                    .addComponent(txtRentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustomer_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarId)
                            .addComponent(jComboBox_Rent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtLast_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirst_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRentDate)
                            .addComponent(txtReturnDate)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPickUp)
                    .addComponent(jComboBox_PickUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Drop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        CabRentalUserRentalMenu al = new CabRentalUserRentalMenu();
        this.hide();
        al.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCustomer_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_IdActionPerformed

    private void txtCustomer_IdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomer_IdKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String Customer_Id = txtCustomer_Id.getText();

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");

                PreparedStatement pstmt = c.prepareStatement("SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID = ?");
                pstmt.setString(1, Customer_Id);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Customer Id Not Found.");
                } else {
                    String First_Name = rs.getString("First_Name");
                    txtFirst_Name.setText(First_Name.trim());

                    String Last_Name = rs.getString("Last_Name");
                    txtLast_Name.setText(Last_Name.trim());
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtCustomer_IdKeyPressed

    private void txtLast_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLast_NameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLast_NameKeyReleased

    private void jComboBox_PickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PickUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PickUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            String Rent_Id = txtRentId.getText();
            String Car_Id = jComboBox_Rent.getSelectedItem().toString();
            String Customer_Id = txtCustomer_Id.getText();

            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            String RentDate = Date_Format.format(jDateChooser1.getDate());

            //        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            String ReturnDate = Date_Format.format(jDateChooser2.getDate());

            String Pick_Up = jComboBox_PickUp.getSelectedItem().toString();
            String Drop = jComboBox_Drop.getSelectedItem().toString();
            String Price = txtPrice.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");

            PreparedStatement pstmt = c.prepareStatement("INSERT INTO RENT(RENT_ID, CAR_ID, CUSTOMER_ID, RENT_DATE, RETURN_DATE, PICKUP_LOCATION, DROP_LOCATION, PRICE) VALUES(?,?,?,?,?,?,?,?)");

            pstmt.setString(1, Rent_Id);
            pstmt.setString(2, Car_Id);
            pstmt.setString(3, Customer_Id);
            pstmt.setString(4, RentDate);
            pstmt.setString(5, ReturnDate);
            pstmt.setString(6, Pick_Up);
            pstmt.setString(7, Drop);
            pstmt.setString(8, Price);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Your Booking Has Been Made!");
            // populateCARS();
            txtRentId.setText("");
            txtCustomer_Id.setText("");
            jDateChooser1.setDate(null);
            jDateChooser2.setDate(null);
            jComboBox_PickUp.setSelectedIndex(-1);
            jComboBox_Drop.setSelectedIndex(-1);
            jComboBox_Rent.setSelectedIndex(-1);
            txtPrice.setText("");
            autoID();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RentActionPerformed
        // TODO add your handling code here:

        try {

            String Car_Id;
            if(jComboBox_Rent.getSelectedItem()==null){
                Car_Id = "";
            }
            else{
                Car_Id = jComboBox_Rent.getSelectedItem().toString();
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            String status = "AVAILABLE";
            PreparedStatement pstmt2 = c.prepareStatement("SELECT * FROM CARS WHERE CAR_ID = ? AND STATUS = ?");
            pstmt2.setString(1, Car_Id);
            pstmt2.setString(2, status);
            ResultSet rs = pstmt2.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "MAKE ANOTHER BOOKING.");
            } else {
                String Price = rs.getString("FEE_PER_DAY");
                txtPrice.setText(Price.trim());
            }

        } catch (ClassNotFoundException | NullPointerException | SQLException ex) {
            Logger.getLogger(RentCar.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jComboBox_RentActionPerformed
public void Update_Table() {

        int r;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            PreparedStatement pstmt = c.prepareStatement("SELECT * FROM CARS WHERE STATUS='Available'");
            ResultSet rs = pstmt.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            r = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) jTableRent.getModel();
            df.setRowCount(0);

            while (rs.next()) {

                Vector v2 = new Vector();

                for (int i = 1; i <= r; i++) {
                    v2.add(rs.getString("CAR_ID"));
                    v2.add(rs.getString("MODEL"));
                    v2.add(rs.getString("MAKE"));
                    v2.add(rs.getString("STATUS"));
                    v2.add(rs.getString("FEE_PER_DAY"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_Drop;
    private javax.swing.JComboBox<String> jComboBox_PickUp;
    private javax.swing.JComboBox<String> jComboBox_Rent;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRent;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPickUp;
    private javax.swing.JLabel lblRentId;
    private javax.swing.JTextField txtCustomer_Id;
    private javax.swing.JTextField txtFirst_Name;
    private javax.swing.JTextField txtLast_Name;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JLabel txtRentDate;
    private javax.swing.JTextField txtRentId;
    private javax.swing.JLabel txtReturnDate;
    // End of variables declaration//GEN-END:variables
}
