/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CarRentalUI;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author shivanirahatwad
 */
public class ReturnCar extends javax.swing.JFrame {

    /**
     * Creates new form ReturnCar
     */
    public ReturnCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttotalCost = new javax.swing.JTextField();
        lblReturnDate = new javax.swing.JLabel();
        btnReturnCar = new javax.swing.JButton();
        lblLateD = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFine = new javax.swing.JLabel();
        lblOGPrice = new javax.swing.JLabel();
        jDateChooser_Return = new com.toedter.calendar.JDateChooser();
        lblTotalCost = new javax.swing.JLabel();
        txtCarId = new javax.swing.JTextField();
        txtCustomerId = new javax.swing.JTextField();
        txtTitle = new javax.swing.JLabel();
        txtLate = new javax.swing.JTextField();
        lblCarId = new javax.swing.JLabel();
        txtFine = new javax.swing.JTextField();
        lblCustomerId = new javax.swing.JLabel();
        txtOGPrice = new javax.swing.JTextField();
        lblRentDate = new javax.swing.JLabel();
        txtRentDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalCostActionPerformed(evt);
            }
        });
        getContentPane().add(txttotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 130, -1));

        lblReturnDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblReturnDate.setText("Return Date:");
        getContentPane().add(lblReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        btnReturnCar.setBackground(new java.awt.Color(153, 204, 255));
        btnReturnCar.setText("Return Car");
        btnReturnCar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnReturnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 130, 30));

        lblLateD.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblLateD.setText("Elapsed:");
        getContentPane().add(lblLateD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 204, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 90, 30));

        lblFine.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFine.setText("Fine:");
        getContentPane().add(lblFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        lblOGPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblOGPrice.setText("Price: ");
        getContentPane().add(lblOGPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));
        getContentPane().add(jDateChooser_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 130, -1));

        lblTotalCost.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTotalCost.setText("Total Cost:");
        getContentPane().add(lblTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        txtCarId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarIdKeyPressed(evt);
            }
        });
        getContentPane().add(txtCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 110, -1));
        getContentPane().add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 120, -1));

        txtTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("RETURN CAR");
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, -1));

        txtLate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLateActionPerformed(evt);
            }
        });
        getContentPane().add(txtLate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 110, -1));

        lblCarId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCarId.setText("Car Id:");
        getContentPane().add(lblCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        txtFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFineActionPerformed(evt);
            }
        });
        getContentPane().add(txtFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 130, -1));

        lblCustomerId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCustomerId.setText("Customer Id:");
        getContentPane().add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        txtOGPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOGPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtOGPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 110, -1));

        lblRentDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRentDate.setText("Rent Date:");
        getContentPane().add(lblRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        txtRentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRentalUI/T2.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, 10, 1290, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalCostActionPerformed

    private void btnReturnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnCarActionPerformed
        // TODO add your handling code here:

        String Car_Id =txtCarId.getText();
        String Customer_Id = txtCustomerId.getText();
        String Rent_Date = txtRentDate.getText();

        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
String Return_Date = Date_Format.format(jDateChooser_Return.getDate());

        String Elapsed = txtLate.getText();
        String Price = txtOGPrice.getText();
        String Fine =txtFine.getText();
        String Total_Cost = txttotalCost.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");

            PreparedStatement pstmt = c.prepareStatement("INSERT INTO RENT(CAR_ID, CUSTOMER_ID,RENT_DATE,RETURN_DATE,ELAPSED,PRICE, FINE, TOTAL_COST) VALUES(?,?,?,?,?,?,?,?)");

            pstmt.setString(1, Car_Id);
            pstmt.setString(2, Customer_Id);
            pstmt.setString(3, Rent_Date);
            pstmt.setString(4, Return_Date);
            pstmt.setString(5, Elapsed);
            pstmt.setString(6, Price);
            pstmt.setString(7, Fine);
            pstmt.setString(8, Total_Cost);
            pstmt.executeUpdate();
            
            

            PreparedStatement pstmt1 = c.prepareStatement("UPDATE CARS SET STATUS = 'AVAILABLE' WHERE CAR_ID=?");
            pstmt1.setString(1, Car_Id);
            pstmt1.executeUpdate();

            PreparedStatement pstmt2 = c.prepareStatement("DELETE FROM RENT WHERE CAR_ID=?");
            pstmt2.setString(1, Car_Id);
            pstmt2.executeUpdate();

            JOptionPane.showMessageDialog(this, "Thank You For Riding With Us!");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReturnCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReturnCar.class.getName()).log(Level.SEVERE, null, ex);
        }

        CabRentalUserRentalMenu al = new   CabRentalUserRentalMenu();
        this.hide();
        al.setVisible(true);

    }//GEN-LAST:event_btnReturnCarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

         CabRentalUserRentalMenu al = new  CabRentalUserRentalMenu();
        this.hide();
        al.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCarIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarIdKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");

                String Car_Id = txtCarId.getText();

                PreparedStatement pstmt = c.prepareStatement("SELECT CAR_ID, CUSTOMER_ID, RENT_DATE, RETURN_DATE, PRICE, DATEDIFF(NOW(),RETURN_DATE)AS ELAPSED, FINE,(PRICE+FINE)AS TOTAL_COST FROM RENT WHERE CAR_ID = ?");
                pstmt.setString(1, Car_Id);
                ResultSet rs = pstmt.executeQuery();

                if(rs.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Car_Id Not Found.");
                }
                else
                {
                    String Customer_Id = rs.getString("CUSTOMER_ID");
                    txtCustomerId.setText(Customer_Id.trim());

                    String Rent_Date = rs.getString("RENT_DATE");
                    txtRentDate.setText(Rent_Date);

                    Date Return_Date = rs.getDate("RETURN_DATE");
                    jDateChooser_Return.setDate(Return_Date);

                    String Elapsed = rs.getString("ELAPSED");
                    int elapsed = Integer.parseInt(Elapsed);

                    if(elapsed > 0)
                    {
                        txtLate.setText("ELAPSED");

                        int Fine = elapsed * 100;

                        txtFine.setText(String.valueOf(Fine));
                    }
                    else
                    {
                        txtLate.setText("0");
                        txtFine.setText("0");

                    }

                    String Price = rs.getString("Price");
                    txtOGPrice.setText(Price.trim());

                    String Total_Cost = rs.getString("TOTAL_COST");
                    txttotalCost.setText(Total_Cost.trim());
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ReturnCar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_txtCarIdKeyPressed

    private void txtLateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLateActionPerformed

    private void txtFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFineActionPerformed

    private void txtOGPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOGPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOGPriceActionPerformed

    private void txtRentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturnCar;
    private com.toedter.calendar.JDateChooser jDateChooser_Return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblFine;
    private javax.swing.JLabel lblLateD;
    private javax.swing.JLabel lblOGPrice;
    private javax.swing.JLabel lblRentDate;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextField txtCarId;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtLate;
    private javax.swing.JTextField txtOGPrice;
    private javax.swing.JTextField txtRentDate;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txttotalCost;
    // End of variables declaration//GEN-END:variables
}
