/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CabBooking_ui;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.awt.event.*;
import javax.swing.border.*;
import javax.swing.JTextField;
import Cab_Booking.ConnectionClass;
import java.util.Random;

/**
 *
 * @author shivanirahatwad
 */
public class BookIntercityCab extends javax.swing.JFrame {

    /**
     * Creates new form BookIntercityCab
     */
    public BookIntercityCab() {
        initComponents();
         
jTextField1.setEditable(false);
jTextField5.setEditable(false);
jTextField6.setEditable(false);
jTextField7.setEditable(false);
jTextField8.setEditable(false);
jTextField9.setEditable(false);
jTextField10.setEditable(false);
        try {
            ConnectionClass con = new ConnectionClass();
            String q = "select source from DriverIntercity";
            ResultSet set = con.s.executeQuery(q);
            while (set.next()) {

                choice1.add(set.getString("source"));

            }
//            set.close();
        } catch (Exception e2) {
            e2.printStackTrace();
        }
        try {
            ConnectionClass con = new ConnectionClass();
            String q = "select username from BookingCustomer";
            ResultSet set = con.s.executeQuery(q);
            while (set.next()) {

                choice3.add(set.getString("username"));

            }
//            set.close();
        } catch (Exception e2) {
            e2.printStackTrace();
        }
//         try {
//            ConnectionClass con = new ConnectionClass();
//            String q = "select destination from DriverIntracity";
//            ResultSet set = con.s.executeQuery(q);
//            while (set.next()) {
//
//                choice3.add(set.getString("destination"));
//
//            }
////            set.close();
//        } catch (Exception e2) {
//            e2.printStackTrace();
//        }
Random rm = new Random();
jTextField1.setText(""+Math.abs(rm.nextInt() % 100000));
jTextField1.setForeground(Color.red);
  
 
 
 
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        choice3 = new java.awt.Choice();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        choice2 = new java.awt.Choice();
        jLabel9 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        choice4 = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Car");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 298, -1, -1));

        btnCancel.setBackground(new java.awt.Color(255, 51, 0));
        btnCancel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 107, -1));

        btnBook.setBackground(new java.awt.Color(255, 255, 0));
        btnBook.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBook.setText("BOOK");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 100, -1));

        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 136, -1, -1));

        jLabel3.setText("Source");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, -1, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 107, -1));

        jLabel2.setText("Book ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 54, -1, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 336, 105, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("BOOK INTRACITY CAB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 51, 107, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 371, 105, -1));

        choice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice3MouseClicked(evt);
            }
        });
        getContentPane().add(choice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 177, 122, -1));

        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 415, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 412, 105, -1));

        jLabel10.setText("Destination to");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 374, -1, -1));

        choice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice2MouseClicked(evt);
            }
        });
        getContentPane().add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 136, 107, -1));

        jLabel9.setText("Destination From");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 339, -1, -1));

        choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice1MouseClicked(evt);
            }
        });
        getContentPane().add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 98, 107, -1));

        jLabel7.setText("Driver Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 259, -1, -1));

        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 218, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 107, -1));

        jLabel12.setText("Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 453, -1, -1));
        getContentPane().add(choice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 453, 122, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CabBooking_ui/drew-beamer-kUHfMW8awpE-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
     String bid = jTextField1.getText();
     String username = choice3.getSelectedItem();
     String dname = jTextField6.getText();
     String car = jTextField10.getText();
     String source = jTextField9.getText();
     String destination = jTextField8.getText();
     String price = jTextField7.getText();
     String type = choice4.getSelectedItem();
     
                  
     
     
     
     try{
         ConnectionClass c = new ConnectionClass();
         String ql = "insert into intercitycabbook values('"+bid+"','"+username+"','"+dname+"','"+car+"','"+source+"','"+destination+"','"+price+"','"+type+"')";
         int aa = c.s.executeUpdate(ql);
         if(aa == 1){
             JOptionPane.showMessageDialog(null,"Cab Booked successfully");
             
            ConfirmationEmail confemail = new ConfirmationEmail();
            confemail.show();
            dispose();
                      
          
         } else {
             JOptionPane.showMessageDialog(null,"Please fill all the details");
         
         }
     } catch (Exception e2) {
            e2.printStackTrace();
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        CabBookHomePage userhome = new CabBookHomePage();
         userhome.show();
         dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void choice3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice3MouseClicked
          try{
       
       ConnectionClass con = new ConnectionClass();
       String username = choice3.getSelectedItem();
       String ql = "select name from BookingCustomer where username = '"+username+"'";
       ResultSet set = con.s.executeQuery(ql);
       while(set.next())
       {
           jTextField5.setText(set.getString("name"));
       }set.close();
       }
       
       catch (Exception e2) {
                    e2.printStackTrace();
		}  
       
       
     
                      
    }//GEN-LAST:event_choice3MouseClicked

    private void choice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseClicked
         choice2.removeAll();
        try{
            ConnectionClass con = new ConnectionClass();
            String source = choice1.getSelectedItem();
            String q1 = "select destination from DriverIntercity where source='"+source+"'";
            ResultSet set = con.s.executeQuery(q1);
            while(set.next())
            {
                choice2.add(set.getString("destination"));
            }
        } catch(Exception exx)
        {
        exx.printStackTrace();
        }
    }//GEN-LAST:event_choice1MouseClicked

    private void choice2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice2MouseClicked
         try{
            ConnectionClass con = new ConnectionClass();
            String source = choice1.getSelectedItem();
            String destination = choice2.getSelectedItem();
            String q1 = "select *  from DriverIntercity where source= '"+source+"' and destination='"+destination+"'";
            ResultSet set = con.s.executeQuery(q1);
            while(set.next())
            {
              jTextField6.setText(set.getString("driver"));
               jTextField10.setText(set.getString("car"));
               jTextField9.setText(set.getString("source"));
          jTextField8.setText(set.getString("destination"));
           jTextField7.setText(set.getString("price"));
                      choice4.add(set.getString("type"));
              
            }
        } catch(Exception exx)
        {
        exx.printStackTrace();
        }
    }//GEN-LAST:event_choice2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookIntercityCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookIntercityCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookIntercityCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookIntercityCab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookIntercityCab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private java.awt.Choice choice3;
    private java.awt.Choice choice4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
