/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CabBooking_ui;
import CarRentalUI.MAINHOME;
import CarServicing_ui.CABSERVICEHOME;
import Reviewsystem_ui.ServiceHome;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author shivanirahatwad
 */
public class MAINUI extends javax.swing.JFrame {
public static String date;
    public static String time;
    /**
     * Creates new form MAINUI
     */
    public MAINUI() {
        initComponents();
        clock();
        test();
        bannerText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        homelbl = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnLogin.setText("BOOK A RIDE");
        btnLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 125, 140, 50));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("CAR RENTALS");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 125, 130, 50));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("CAR SERVICING");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, 50));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("CUSTOMER CARE");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 140, 50));

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setText("LOGIN AS A SYSTEM ADMIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        homelbl.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        homelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homelbl.setText("BON VOYAGE");
        getContentPane().add(homelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 40));

        time1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 40));

        date1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CabBooking_ui/C.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -270, 1080, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         
            CabBookMain  csh3 = new    CabBookMain();
        this.hide();
        csh3.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
                MAINHOME  csh3 = new   MAINHOME ();
        this.hide();
        csh3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        CABSERVICEHOME  csh3 = new   CABSERVICEHOME ();
        this.hide();
        csh3.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ServiceHome  csh3 = new   ServiceHome ();
        this.hide();
        csh3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          SystemAdminLogin  csh3 = new   SystemAdminLogin  ();
        this.hide();
        csh3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel homelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel time1;
    // End of variables declaration//GEN-END:variables

    private void clock() {
        Thread clock=new Thread()
                {
                public void run()
                {
                    try {
                   while(true)
                       {
                        Calendar cal=new GregorianCalendar();
                        int day=cal.get(Calendar.DAY_OF_MONTH);
                        int month=cal.get(Calendar.MONTH)+1;
                        int year=cal.get(Calendar.YEAR);

                        int second=cal.get(Calendar.SECOND);
                        int minute=cal.get(Calendar.MINUTE);
                        int hour=cal.get(Calendar.HOUR);

                        time1.setText( hour +":"+ minute +":"+ second);
                        date1.setText( year +"-"+ month +"-"+ day );
                      time=time1.getText();
                      date = date1.getText();
                                        sleep(1000);
                        }
                    } catch (InterruptedException ex) {
                       // Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                       
                    }
                }
            };
        clock.start();
    }

    private void test() {
       Thread test=new Thread()
                {
                public void run()
                {
                    try {
                   while(true)
                       {
                     //   homelbl.setText("");
                           for(int x=0; x<4; x++)
                           {
                         //  homelbl.setText("");
                           if(x==0)
                           {
                           homelbl.setText("");
                           }
                           else if(x==1)
                           {
                           homelbl.setText("BON");
                           }
                           else if(x==2)
                           {
                           homelbl.setText("BONVOY");
                           }
                           if(x==3)
                           {
                           homelbl.setText("BONVOYAGE");
                           }
                            sleep(1000); 
                           }
                                      
                        }
                    } catch (InterruptedException ex) {
                       // Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                       
                    }
                }
            };
        test.start();
    }

    private void bannerText() {
//         Thread banner=new Thread()
//                {
//                public void run()
//                {
//                    try {
//                   while(true)
//                       {
//                     //   homelbl.setText("");
//                           for(int x=0; x<3; x++)
//                           {
//                         //  homelbl.setText("");
//                               
//                          lblbanner.setText("What's Our Services :  "+bannerText[x]);
//                            sleep(3000); 
//                           }
//                                      
//                        }
//                    } catch (InterruptedException ex) {
//                       // Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
//                       
//                    }
//                }
//            };
//        banner.start();  
    }}
