/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author tanvikakde
 */
public class AdminLoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoginJFrame
     */
    public AdminLoginJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnALogin = new javax.swing.JButton();
        btnABack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblAUsername = new javax.swing.JLabel();
        lblAPassword = new javax.swing.JLabel();
        txtAUsername = new javax.swing.JTextField();
        jAPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnALogin.setBackground(new java.awt.Color(255, 204, 204));
        btnALogin.setText("LOGIN");
        btnALogin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnALogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnALogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 60, 20));

        btnABack.setBackground(new java.awt.Color(255, 204, 204));
        btnABack.setText("BACK");
        btnABack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnABack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABackActionPerformed(evt);
            }
        });
        getContentPane().add(btnABack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 60, 20));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("ADMIN LOGIN");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblAUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAUsername.setText("USERNAME:");
        getContentPane().add(lblAUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        lblAPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAPassword.setText("PASSWORD:");
        getContentPane().add(lblAPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        txtAUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtAUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, -1));
        getContentPane().add(jAPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/car2.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnALoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALoginActionPerformed
        // TODO add your handling code here:

        String username = txtAUsername.getText();
        String password = jAPassword.getText();

        if(username.equals("admin") && password.equals("admin123")){
            AdminMainMenueJFrame c = new AdminMainMenueJFrame();
            this.hide();
            c.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Incorrect Username/Password");
        }
    }//GEN-LAST:event_btnALoginActionPerformed

    private void txtAUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAUsernameActionPerformed

    private void btnABackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABackActionPerformed
        // TODO add your handling code here:
        
        MainJFrame ur = new MainJFrame();
        this.hide();
        ur.setVisible(true);
    }//GEN-LAST:event_btnABackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnABack;
    private javax.swing.JButton btnALogin;
    private javax.swing.JPasswordField jAPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAPassword;
    private javax.swing.JLabel lblAUsername;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAUsername;
    // End of variables declaration//GEN-END:variables
}
