/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import static java.awt.AWTEventMulticaster.add;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanvikakde
 */
public class CarRegistrationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CarRegistrationJFrame
     */
    public CarRegistrationJFrame() {
        initComponents();
        autoID();
        Update_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCarId = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblFeePerDay = new javax.swing.JLabel();
        txtCarId = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        CBStatus = new javax.swing.JComboBox<>();
        txtFeePerDay = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setText("Car Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, 50));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCarId.setText("Car Id:");
        jPanel1.add(lblCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lblModel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblModel.setText("Model:");
        jPanel1.add(lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblMake.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblMake.setText("Make:");
        jPanel1.add(lblMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblStatus.setText("Status:");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lblFeePerDay.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFeePerDay.setText("Fee Per Day:");
        jPanel1.add(lblFeePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtCarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 144, -1));
        jPanel1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 143, -1));
        jPanel1.add(txtMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 141, -1));

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Available", "Booked" }));
        CBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStatusActionPerformed(evt);
            }
        });
        jPanel1.add(CBStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        txtFeePerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeePerDayActionPerformed(evt);
            }
        });
        jPanel1.add(txtFeePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 102, -1));

        btnAdd.setBackground(new java.awt.Color(255, 204, 204));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 204, 204));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 67, 330, 480));

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Model", "Make", "Status", "Fee Per Day"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayMouseClicked(evt);
            }
        });
        tblDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDisplayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDisplayKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblDisplay);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 484, 250));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/car1.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void autoID() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            Statement s = c.createStatement();

            ResultSet rs = s.executeQuery("SELECT MAX(CAR_ID) FROM CARS");
            rs.next();
            rs.getString("MAX(CAR_ID)");

            if (rs.getString("MAX(CAR_ID)") == null) {
                txtCarId.setText("C0001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(CAR_ID)").substring(2, rs.getString("MAX(CAR_ID)").length()));
                id++;

                txtCarId.setText("C0" + String.format("%03d", id));

            }

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }

    public void Update_Table() {

        int r;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            PreparedStatement pstmt = c.prepareStatement("SELECT * FROM CARS");
            ResultSet rs = pstmt.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            r = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) tblDisplay.getModel();
            df.setRowCount(0);

            while (rs.next()) {

                Vector v2 = new Vector();

                for (int i = 1; i <= r; i++) {
                    v2.add(rs.getString("CAR_ID"));
                    v2.add(rs.getString("MODEL"));
                    v2.add(rs.getString("MAKE"));
                    v2.add(rs.getString("STATUS"));
                    v2.add(rs.getString("FEE_PER_DAY"));

                }
                df.addRow(v2);

            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    private void txtCarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarIdActionPerformed

    private void CBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStatusActionPerformed

    private void txtFeePerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeePerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeePerDayActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");

            String Car_Id = txtCarId.getText();
            String Model = txtModel.getText();
            String Make = txtMake.getText();
            String Status = (String) CBStatus.getSelectedItem();
            String Fee_Per_Day = txtFeePerDay.getText();

            Statement stm = c.createStatement();
            //String sql = "Insert into cars values(?,?,?,?,?)";
            PreparedStatement pstmt = c.prepareStatement("INSERT INTO CARS(CAR_ID, MODEL, MAKE, STATUS, FEE_PER_DAY) VALUES(?,?,?,?,?)");
            pstmt.setString (1,Car_Id);
            pstmt.setString(2, Model);
            pstmt.setString(3, Make);
            pstmt.setString(4, Status);
            pstmt.setString(5, Fee_Per_Day);
     
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Car Has Been Added!");
           // populateCARS();
            txtCarId.setText("");
            txtModel.setText("");
            txtMake.setText("");
            CBStatus.setSelectedIndex(-1);
            txtFeePerDay.setText("");
            txtModel.requestFocus();
            autoID();
            Update_Table();

            c.close();


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel d1 = (DefaultTableModel)tblDisplay.getModel();
        
        int selectIndex = tblDisplay.getSelectedRow();
        
        try {
            
            String Car_Id = txtCarId.getText();
            String Model = txtModel.getText();
            String Make= txtMake.getText();
            String Status = CBStatus.getSelectedItem().toString();
            String Fee_Per_Day = txtFeePerDay.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            
           PreparedStatement pstmt = c.prepareStatement("UPDATE CARS SET MODEL=?, MAKE=?, STATUS=?, FEE_PER_DAY=? WHERE CAR_ID=?");
            
           
            pstmt.setString(1, Model);
            pstmt.setString(2, Make);
            pstmt.setString(3, Status);
            pstmt.setString(4, Fee_Per_Day);
            pstmt.setString (5,Car_Id);
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Details Have Been Updated!");
            
            Update_Table(); 
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CarRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CarRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel d1 = (DefaultTableModel)tblDisplay.getModel();
        
        int selectIndex = tblDisplay.getSelectedRow();
        
        
        String Car_Id = d1.getValueAt(selectIndex, 0).toString();
        
        int dialogResult = JOptionPane.showConfirmDialog(this,"Are You Sure You Want To Delete This Record?","WARNING",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION)
        {
           try{
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
               
               PreparedStatement pstmt = c.prepareStatement("DELETE FROM CARS WHERE CAR_ID=?");
               
               pstmt.setString(1, Car_Id);
               pstmt.executeUpdate();
               
               JOptionPane.showMessageDialog(this, "Details Have Been Deleted!");
               
               Update_Table();
               
              } catch (ClassNotFoundException ex) {
                  Logger.getLogger(CarRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
              } catch (SQLException ex) {
                  Logger.getLogger(CarRegistrationJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        AdminMainMenueJFrame amm = new AdminMainMenueJFrame();
        this.hide();
        amm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblDisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDisplayKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tblDisplayKeyPressed

    private void tblDisplayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDisplayKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDisplayKeyReleased

    private void tblDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel d1 = (DefaultTableModel)tblDisplay.getModel();
        
        int selectIndex = tblDisplay.getSelectedRow();
        
        txtCarId.setText(d1.getValueAt (selectIndex, 0).toString());
        txtModel.setText(d1.getValueAt (selectIndex, 1).toString());
        txtMake.setText(d1.getValueAt (selectIndex, 2).toString());
        CBStatus.setSelectedItem(d1.getValueAt (selectIndex, 3).toString());
        txtFeePerDay.setText(d1.getValueAt (selectIndex, 4).toString());
        
        
    }//GEN-LAST:event_tblDisplayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRegistrationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblFeePerDay;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtCarId;
    private javax.swing.JTextField txtFeePerDay;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
