
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author madhulikadekate
 */
public class HomeJFrame extends javax.swing.JFrame {
    Process pr=null;
    String path=null;
    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listBtn = new javax.swing.JButton();
        onBtn = new javax.swing.JButton();
        hisBtn = new javax.swing.JButton();
        nxtBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        serLab = new javax.swing.JLabel();
        custBtn = new javax.swing.JButton();
        vhBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        resultBtn = new javax.swing.JButton();
        rtnBtn = new javax.swing.JButton();
        repBtn = new javax.swing.JButton();
        cleanBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listBtn.setBackground(new java.awt.Color(204, 204, 255));
        listBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        listBtn.setText("Customer List");
        listBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });
        getContentPane().add(listBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 159, 32));

        onBtn.setBackground(new java.awt.Color(204, 204, 255));
        onBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        onBtn.setText("On Going Service");
        onBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        onBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBtnActionPerformed(evt);
            }
        });
        getContentPane().add(onBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 159, 32));

        hisBtn.setBackground(new java.awt.Color(204, 204, 255));
        hisBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        hisBtn.setText("Service History");
        hisBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        hisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hisBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hisBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 159, 32));

        nxtBtn.setBackground(new java.awt.Color(204, 204, 255));
        nxtBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nxtBtn.setText("Next Service");
        nxtBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        nxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nxtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 159, 32));

        upBtn.setBackground(new java.awt.Color(204, 204, 255));
        upBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        upBtn.setText("Backup");
        upBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });
        getContentPane().add(upBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 159, 32));

        serLab.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        serLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serLab.setText("Car Servicing Center");
        getContentPane().add(serLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 819, 60));

        custBtn.setBackground(new java.awt.Color(204, 204, 255));
        custBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        custBtn.setText("Customer");
        custBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        custBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        custBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custBtnActionPerformed(evt);
            }
        });
        getContentPane().add(custBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 150, 222, 32));

        vhBtn.setBackground(new java.awt.Color(204, 204, 255));
        vhBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        vhBtn.setText("Vehicle");
        vhBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        vhBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vhBtnActionPerformed(evt);
            }
        });
        getContentPane().add(vhBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 209, 222, 32));

        addBtn.setBackground(new java.awt.Color(204, 204, 255));
        addBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addBtn.setText("Add to Service");
        addBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 267, 222, 32));

        resultBtn.setBackground(new java.awt.Color(204, 204, 255));
        resultBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        resultBtn.setText("Service Result");
        resultBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        resultBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resultBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 325, 222, 32));

        rtnBtn.setBackground(new java.awt.Color(204, 204, 255));
        rtnBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        rtnBtn.setText("Vehicle Return");
        rtnBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        rtnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rtnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rtnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 383, 222, 32));

        repBtn.setBackground(new java.awt.Color(204, 204, 255));
        repBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        repBtn.setText("Repair (W)");
        repBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        repBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        repBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repBtnActionPerformed(evt);
            }
        });
        getContentPane().add(repBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 441, 222, 32));

        cleanBtn.setBackground(new java.awt.Color(204, 204, 255));
        cleanBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cleanBtn.setText("Cleaning (W)");
        cleanBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cleanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cleanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 499, 222, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/madhulikadekate/Desktop/car-1.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -10, 1190, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtBtnActionPerformed
        // TODO add your handling code here:
        NextServiceJFrame NextService = new NextServiceJFrame();
        this.hide();
         NextService.setVisible(true);
                  
    }//GEN-LAST:event_nxtBtnActionPerformed

    private void custBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custBtnActionPerformed
        // TODO add your handling code here:
        CustomerJFrame Customer = new CustomerJFrame();
        this.hide();
         Customer.setVisible(true);
     
        
    }//GEN-LAST:event_custBtnActionPerformed

    private void vhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vhBtnActionPerformed
        // TODO add your handling code here:
        VehicalJFrame Vehicle = new VehicalJFrame();
       this.hide();
         Vehicle.setVisible(true);
        
    }//GEN-LAST:event_vhBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        AddServiceJFrame Add = new AddServiceJFrame();
        this.hide();
         Add.setVisible(true);
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void rtnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtnBtnActionPerformed
        // TODO add your handling code here:
        VehicalReturnJFrame Return = new  VehicalReturnJFrame();
       this.hide();
        Return.setVisible(true);
        
    }//GEN-LAST:event_rtnBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:        
        CustomerListJFrame List = new CustomerListJFrame();
     this.hide();
         List.setVisible(true);
    }//GEN-LAST:event_listBtnActionPerformed

    private void onBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBtnActionPerformed
        // TODO add your handling code here:
        OnServiceJFrame OnService = new OnServiceJFrame();
        this.hide();
        OnService.setVisible(true);
    }//GEN-LAST:event_onBtnActionPerformed

    private void hisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hisBtnActionPerformed
        // TODO add your handling code here:
        ServiceHistoryJFrame History = new ServiceHistoryJFrame();
       this.hide();
       History.setVisible(true);
            
    }//GEN-LAST:event_hisBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:
        BackupJFrame Backup = new BackupJFrame();
        this.hide();
        Backup.setVisible(true);
                   
    }//GEN-LAST:event_upBtnActionPerformed

    private void resultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBtnActionPerformed
        // TODO add your handling code here:
        ServiceResultJFrame Result = new ServiceResultJFrame();
       this.hide();
        Result.setVisible(true);
        
    }//GEN-LAST:event_resultBtnActionPerformed

    private void repBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repBtnActionPerformed
        // TODO add your handling code here:
        RepairJFrame Repair = new RepairJFrame();
        this.hide();
        Repair.setVisible(true);
    }//GEN-LAST:event_repBtnActionPerformed

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        // TODO add your handling code here:
        CleaningJFrame Cleaning = new CleaningJFrame();
        this.hide();
        Cleaning.setVisible(true);
    }//GEN-LAST:event_cleanBtnActionPerformed
     private void backup()
    {
        
        String date=new SimpleDateFormat("yyy-MM-dd").format(new Date());
        path="G:\\";
         path = path + "_" + date + ".sql";
        try {
            Runtime run= Runtime.getRuntime();
            pr=run.exec("C://wamp64//bin//mysql//mysql5.7.21//bin//mysqldump.exe -uroot  --add-drop-database -B computer_shop -r"+ path);
            
            int processComplete= pr.waitFor();
            if(processComplete==0)
            {
           // JOptionPane.showMessageDialog(rootPane, "Backup Success");
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Fail");
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JButton custBtn;
    private javax.swing.JButton hisBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton listBtn;
    private javax.swing.JButton nxtBtn;
    private javax.swing.JButton onBtn;
    private javax.swing.JButton repBtn;
    private javax.swing.JButton resultBtn;
    private javax.swing.JButton rtnBtn;
    private javax.swing.JLabel serLab;
    private javax.swing.JButton upBtn;
    private javax.swing.JButton vhBtn;
    // End of variables declaration//GEN-END:variables
}
