/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author tanvikakde
 */
public class ReturnJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReturnJFrame
     */
    public ReturnJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttotalCost = new javax.swing.JTextField();
        lblReturnDate = new javax.swing.JLabel();
        btnReturnCar = new javax.swing.JButton();
        lblLateD = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblFine = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblOGPrice = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblTotalCost = new javax.swing.JLabel();
        txtCarId = new javax.swing.JTextField();
        txtCustomerId = new javax.swing.JTextField();
        txtTitle = new javax.swing.JLabel();
        txtLate = new javax.swing.JTextField();
        lblCarId = new javax.swing.JLabel();
        txtFine = new javax.swing.JTextField();
        lblCustomerId = new javax.swing.JLabel();
        txtOGPrice = new javax.swing.JTextField();
        lblRentDate = new javax.swing.JLabel();
        lblRent_Id = new javax.swing.JLabel();
        txtRent_Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txttotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 73, -1));

        lblReturnDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblReturnDate.setText("Return Date:");
        getContentPane().add(lblReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        btnReturnCar.setBackground(new java.awt.Color(255, 204, 204));
        btnReturnCar.setText("Return Car");
        btnReturnCar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnReturnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 30));

        lblLateD.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblLateD.setText("Days Elapsed:");
        getContentPane().add(lblLateD, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 40, 30));

        lblFine.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFine.setText("Fine:");
        getContentPane().add(lblFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        lblOGPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblOGPrice.setText("Price: ");
        getContentPane().add(lblOGPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 251, -1, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        lblTotalCost.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTotalCost.setText("Total Cost:");
        getContentPane().add(lblTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));
        getContentPane().add(txtCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 93, -1));
        getContentPane().add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 73, -1));

        txtTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        txtTitle.setText("RETURN CAR");
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        txtLate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLateActionPerformed(evt);
            }
        });
        getContentPane().add(txtLate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 95, -1));

        lblCarId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCarId.setText("Car Id:");
        getContentPane().add(lblCarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 128, -1, -1));

        txtFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFineActionPerformed(evt);
            }
        });
        getContentPane().add(txtFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 83, -1));

        lblCustomerId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCustomerId.setText("Customer Id:");
        getContentPane().add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));
        getContentPane().add(txtOGPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 95, -1));

        lblRentDate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRentDate.setText("Rent Date:");
        getContentPane().add(lblRentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 166, -1, -1));

        lblRent_Id.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRent_Id.setText("Rent_Id:");
        getContentPane().add(lblRent_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 87, -1, -1));
        getContentPane().add(txtRent_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 91, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/car1.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnCarActionPerformed

    private void txtLateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLateActionPerformed

    private void txtFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFineActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        UserRentalMenuJFrame al = new UserRentalMenuJFrame();
        this.hide();
        al.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturnCar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblFine;
    private javax.swing.JLabel lblLateD;
    private javax.swing.JLabel lblOGPrice;
    private javax.swing.JLabel lblRentDate;
    private javax.swing.JLabel lblRent_Id;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextField txtCarId;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtLate;
    private javax.swing.JTextField txtOGPrice;
    private javax.swing.JTextField txtRent_Id;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextField txttotalCost;
    // End of variables declaration//GEN-END:variables
}