/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author tanvikakde
 */
public class UserRegistrationJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserRegistrationJFrame
     */
    public UserRegistrationJFrame() {
        initComponents();
        autoID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmailid = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtCustomerId = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblCustomerId = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtEmailid = new javax.swing.JTextField();
        textAreaAddress = new java.awt.TextArea();
        Date_Of_Birth = new com.toedter.calendar.JDateChooser();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jPasswordField_Re = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailid.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblEmailid.setText("EMAIL ID:");
        getContentPane().add(lblEmailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 426, -1, -1));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblTitle.setText("CUSTOMER REGISTRATION");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 338, -1));

        btnCreateAccount.setBackground(new java.awt.Color(255, 204, 204));
        btnCreateAccount.setText("CREATE ACCOUNT");
        btnCreateAccount.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 534, 120, 30));

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 534, 91, 30));

        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 72, 135, -1));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 113, 135, -1));

        lblCustomerId.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCustomerId.setText("CUSTOMER ID:");
        getContentPane().add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 75, -1, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 154, 135, -1));

        lblFirstName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFirstName.setText("FIRST NAME:");
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 116, -1, -1));

        lblLastName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblLastName.setText("LAST NAME:");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 157, -1, -1));

        lblDob.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDob.setText("DOB:");
        getContentPane().add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 318, -1, -1));

        lblAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblAddress.setText("ADDRESS:");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 364, -1, -1));
        getContentPane().add(txtEmailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 423, 287, -1));
        getContentPane().add(textAreaAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 364, 225, 46));
        getContentPane().add(Date_Of_Birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 318, 137, -1));

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblUsername.setText("USERNAME:");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 198, -1, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 195, 135, -1));

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblPassword.setText("PASSWORD:");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 233, -1, -1));

        lblConfirmPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblConfirmPassword.setText("CONFIRM PASSWORD:");
        getContentPane().add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, -1, -1));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 136, -1));
        getContentPane().add(jPasswordField_Re, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 265, 136, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/WhatsApp Image 2022-12-11 at 4.25.30 PM (1).jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void autoID() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            Statement s = c.createStatement();

            ResultSet rs = s.executeQuery("SELECT MAX(CUSTOMER_ID) FROM CUSTOMERS");
            rs.next();
            rs.getString("MAX(CUSTOMER_ID)");

            if (rs.getString("MAX(CUSTOMER_ID)") == null) {
                txtCustomerId.setText("CU001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(CUSTOMER_ID)").substring(2, rs.getString("MAX(CUSTOMER_ID)").length()));
                id++;

                txtCustomerId.setText("CU" + String.format("%03d", id));

            }

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }
    
    
    
    private static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
        if (date!=null){
            java.sql.Date sqlDate = new java.sql.Date(date.getDate());
            return sqlDate;
        }
        return null;
    }
    
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        
        
        try {
            
//              String DOB = new SimpleDateFormat("yyyy-MM-dd").format(new Date(request.getParameter("date")));

              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");

            String Customer_Id = txtCustomerId.getText();
            String First_Name = txtFirstName.getText();
            String Last_Name = txtLastName.getText();
            String Username = txtUsername.getText();
            String Pass_word = String.valueOf(jPassword.getPassword());
            String Confirm_Password = String.valueOf(jPasswordField_Re.getPassword());
            java.util.Date DOB = Date_Of_Birth.getDate();
            String Address = textAreaAddress.getText();
            String Email_Id = txtEmailid.getText();

            Statement stm = c.createStatement();
            //String sql = "Insert into cars values(?,?,?,?,?)";
            PreparedStatement pstmt = c.prepareStatement("INSERT INTO CUSTOMERS(CUSTOMER_ID, FIRST_NAME, LAST_NAME, USER_NAME, PASS_WORD, DOB, ADDRESS, EMAIL_ID) VALUES(?,?,?,?,?,?,?,?)");
            pstmt.setString (1,Customer_Id);
            pstmt.setString(2, First_Name);
            pstmt.setString(3, Last_Name);
            pstmt.setString(4, Username);
            pstmt.setString(5, Pass_word);
            pstmt.setDate(6, convertUtilDateToSqlDate(DOB));
            pstmt.setString(7, Address);
            pstmt.setString(8, Email_Id);
     
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Your Account Has Been Created, Kindly Login To Continue.");
            
            txtCustomerId.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtUsername.setText("");
            jPassword.setText("");
            jPasswordField_Re.setText("");
            textAreaAddress.setText("");
            textAreaAddress.setText("");
            
            txtCustomerId.requestFocus();
            autoID();
           

            c.close();


        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        UserLoginJFrame al = new  UserLoginJFrame();
        this.hide();
        al.setVisible(true);
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        UserLoginJFrame ul = new UserLoginJFrame();
        this.hide();
        ul.setVisible(true);       
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistrationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_Of_Birth;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordField_Re;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmailid;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private java.awt.TextArea textAreaAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtEmailid;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
