
package Interface;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.data.JRTableModelDataSource;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author madhulikadekate
 */
public class R_items extends javax.swing.JInternalFrame {

    /**
     * Creates new form LapTop
     */
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    String sqr;
    
    public R_items() throws SQLException {
        initComponents();
        conn=DBConnect.connect();
      //  autoId();
        tablelord();
    }

    private void tablelord()
    {
        try {
            String sql="SELECT `sid` as 'Service ID', `vnumber` as 'Vehicle Number', `model` as 'Model', `modelname` as 'Model Name', `nic` as 'NIC', `oname` as 'Client Name', `stype` as 'Service Type', `date` as 'Date' FROM `add_to_service` WHERE status='0'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblallitem.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            theader();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
      // theader();
    }
    
     private void  theader()
    {
    JTableHeader thead = tblallitem.getTableHeader();
       thead.setForeground(Color.BLUE);
    
       thead.setFont(new Font("Tahome", Font.BOLD, 14));
       
        TableColumn col1=tblallitem.getColumnModel().getColumn(0);
        col1.setPreferredWidth(120);
        TableColumn col2=tblallitem.getColumnModel().getColumn(1);
        col2.setPreferredWidth(120);
        TableColumn col3=tblallitem.getColumnModel().getColumn(2);
        col3.setPreferredWidth(120);
        TableColumn col4=tblallitem.getColumnModel().getColumn(3);
        col4.setPreferredWidth(120);
        TableColumn col5=tblallitem.getColumnModel().getColumn(4);
        col5.setPreferredWidth(120);
        TableColumn col6=tblallitem.getColumnModel().getColumn(5);
        col6.setPreferredWidth(120);
        TableColumn col7=tblallitem.getColumnModel().getColumn(6);
        col7.setPreferredWidth(120);
        TableColumn col8=tblallitem.getColumnModel().getColumn(7);
        col8.setPreferredWidth(120);
       
        
    }
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcusname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblallitem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/print32.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 190, 40));

        btnclear.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clear.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 190, 40));

        jLabel20.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("On the Service");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 20));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 45, 86));
        jLabel16.setText("NIC");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 100, 20));

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 270, 30));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 45, 86));
        jLabel5.setText("Vehicle Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtcusname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcusnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtcusname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 190, 30));

        tblallitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblallitem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tblallitem);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 830, 310));

        jPanel2.setBackground(new java.awt.Color(190, 2, 1));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
      
            try {

            String parseSql="SELECT `sid` as 'Service ID', `vnumber` as 'Vehicle Number', `model` as 'Model', `modelname` as 'Model Name', `nic` as 'NIC', `oname` as 'Client Name', `stype` as 'Service Type', `date` as 'Date' FROM `add_to_service` WHERE status='0' AND nic='"+txtsearch.getText()+"'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tblallitem.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            theader();

        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
           int prcount=tblallitem.getRowCount();
    if(prcount>0)
    {
        DefaultTableModel tableModel=(DefaultTableModel)tblallitem.getModel();
        try {
            // HashMap<String, Object> para=new HashMap<>();
            // para.put("tittle","Sale Report");
            // TableModelData();
//             JasperPrint jasperPrint = null;
//             JasperCompileManager.compileReportToFile("C:\\Users\\ccs\\Documents\\NetBeansProjects\\ComputerService\\src\\report\\allReceive.jrxml");
//             jasperPrint = JasperFillManager.fillReport("C:\\Users\\ccs\\Documents\\NetBeansProjects\\ComputerService\\src\\report\\allReceive.jasper", null,
//             new JRTableModelDataSource(tableModel));
//             JasperViewer.viewReport(jasperPrint, false);
            
            tblallitem.print();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "Not Details to print");
    }    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
      
        txtcusname.setText("");
        txtsearch.setText("");
    
     tablelord();
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtcusnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusnameKeyReleased
       
          try {

            String parseSql="SELECT `sid` as 'Service ID', `vnumber` as 'Vehicle Number', `model` as 'Model', `modelname` as 'Model Name', `nic` as 'NIC', `oname` as 'Client Name', `stype` as 'Service Type', `date` as 'Date' FROM `add_to_service` WHERE status='0' AND vnumber='"+txtcusname.getText()+"'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tblallitem.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            theader();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_txtcusnameKeyReleased

    private void allitem()
    {
    
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblallitem;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
