/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reviewsystem_ui;



import CabBooking_ui.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message.RecipientType;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author shivanirahatwad
 */
public class ConfirmationEmail extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmationEmail
     */
    public ConfirmationEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEmailAdd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSendEmail = new javax.swing.JButton();
        jLabelResponse = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldEmailAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextFieldEmailAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 249, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("ENTER YOUR EMAIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jButtonSendEmail.setBackground(new java.awt.Color(255, 255, 51));
        jButtonSendEmail.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonSendEmail.setText("CONFIRM");
        jButtonSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));
        getContentPane().add(jLabelResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 610, 55));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("PLEASE CHECK YOUR EMAIL FOR CODE AFTER CONFIRM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 400, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CabBooking_ui/H.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, -10, 1210, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendEmailActionPerformed
        Properties props = new Properties();
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ConfirmationEmail.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.port",465);
        props.put("mail.smtp.user","shivanirahatwad3299@gmail.com");
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.debug","true");
        props.put("mail.smtp.socketFactory.port",465);
        props.put("mail.smtp.socketFactory.class","javax.neet.ssl.SSLSocketFactory");
        props.put("mail.smtp.socketFactory.fallback","false");
        
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/BONVOYAGE", "root", "shivani3299");
            PreparedStatement pstmt = c.prepareStatement("SELECT dob FROM BookingCustomer where emailaddress LIKE'"+jTextFieldEmailAdd.getText().trim()+"'");
            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
            {
            String fetcheddob = rs.getString("dob");
            Session session = Session.getDefaultInstance(props,null);
            session.setDebug(true);
            MimeMessage message = new MimeMessage(session);
            message.setText("Your Ride is confirmed ,Your driver will call you shortly.Your OTp is" + fetcheddob);
            message.setSubject("Your Ride is confirmed");
            message.setFrom(new InternetAddress("shivanirahatwad3299@gmail.com"));
            message.addRecipient(RecipientType.TO,new InternetAddress(jTextFieldEmailAdd.getText().trim()));
            message.saveChanges();
            Transport transport = session.getTransport("smtp");
            transport.connect("smtp.gmail.com","my_gmail_id","my_gmailpassword");
            transport.sendMessage(message,message.getAllRecipients());
            transport.close();
            jLabelResponse.setText("Your Ride has been booked,please check email for confirmation");
           
            }

        
        }catch (ClassNotFoundException | SQLException | MessagingException ex) {
           
        }
        
        
    }//GEN-LAST:event_jButtonSendEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConfirmationEmail().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelResponse;
    private javax.swing.JTextField jTextFieldEmailAdd;
    // End of variables declaration//GEN-END:variables
}
